name: Deploy  CI

on:
  push:
    branches:
      - 自动合并分支

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependent & Build
      run: |
        npm install
        npm install -g hexo-cli
        hexo g

#    - name: Commit
#      run: |
#        git config --global user.email hocgin@gmail.com
#        git config --global user.name hocgin
#        git add public/*
#        git commit -m '部署' -a

    - name: Push
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: public
