name: Deploy CI

on:
  push:
    branches:
      - 自动合并分支

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependent & Build
      run: |
        npm install
        npm install -g hexo
        hexo g

    - name: Push
      uses: JamesIves/github-pages-deploy-action@releases/v2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
