name: Node.js CI

on:
  push:
    branches:
      - 自动合并分支

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        BRANCH: master
        FOLDER: public
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_SCRIPT: npm install && npm run build && hexo g
